# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32fb64c4fac9b992114e15ffe676493e9c6a17c2b0e9e6bea7885eff66ee302baff9ef5216c0479847e5aa7cdeb772ccb35d99a5390ad9edede60cf4b1bdc1ed

test:
  secret_key_base: daeaab4dd389a7e36a3529afb921602f40618d009491d012defcf4ae1740c0684be3f07dada799d9b4e888020cabceeb6845e56db27405e70b2a678e42f3e8d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
